# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7827f618a617b8a97a13145c33375393436129ab1121f1213d733ee5fa9fc4b4364f0a6cbbf04b53b4a7c0e4832c74eb0d8f77179303f6e22e29445fdfda4c74
  dropbox_access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>

test:
  secret_key_base: 4723ff6a30779869aa8d7bb1f414a7c651441e4d6090eefa2987736292818d1ac98be9f81ffc20d00faa3de2bdb7a790ab486e2890aa14a114f9c0a84acaf321

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  dropbox_access_token: <%= ENV['DROPBOX_ACCESS_TOKEN'] %>
